[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_jsonrc.workspace = true
serde.workspace = true
tokio.workspace = true
async-channel.workspace = true
log.workspace = true
util.workspace = true
