[package]
name = "way-edges-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.70", features = ["extra-traits", "fold", "full"] }
proc-macro2 = "1.0.81"
proc-macro-crate = "3.2.0"

[lib]
proc-macro = true
